import streamlit as st

def render_movie_card(movie_data, explanation):
    """
    Renders a nice UI card for a single movie.
    """
    # CSS for the card
    card_style = f"""
    <div style="
        background-color: #262730;
        padding: 15px;
        border-radius: 10px;
        border-left: 5px solid {movie_data['poster_color']};
        margin-bottom: 10px;
    ">
        <h3 style="margin:0; color: white;">{movie_data['title']} <span style="font-size:12px; color:#aaa">({movie_data['year']})</span></h3>
        <p style="margin:0; color: #ddd; font-style: italic;">{movie_data['genre']}</p>
        <hr style="border-color: #444;">
        <p style="font-size: 14px; color: #bbb;">{explanation}</p>
        <div style="display: flex; justify-content: space-between; align-items: center; margin-top: 10px;">
            <span style="background-color: #444; padding: 2px 8px; border-radius: 4px; font-size: 12px;">Predicted: ⭐ {movie_data['rating']:.1f}</span>
            <span style="font-size: 12px; color: #aaa;">Uncertainty: {movie_data['sigma']:.2f}</span>
        </div>
    </div>
    """
    st.markdown(card_style, unsafe_allow_html=True)




# """
# CODE EXPLANATION:
# 1. render_movie_card():
#    - Standard Pandas Dataframes are ugly. This function creates a "Netflix-style" UI card.
#    - It uses HTML/CSS injection (st.markdown(..., unsafe_allow_html=True)) to style the component.
#    - Color Coding: The left border color changes based on the Genre (defined in mock_database.py).
#    - Content: It combines the Title, Year, Genre, and the Natural Language Explanation generated by explanation.py.
#    - Purpose: To demonstrate Frontend/UX skills alongside Data Science skills.
# """